### PR TITLE
Added cause when rethrowing exceptions in connectAndBind method

### PR DESCRIPTION
**Pull request by pruh**
When rethrowing an exception in connectAndBind method it's good to know the cause of the exception. For example if the original exception was NegativeResponseException we can retrieve command_status and act accordingly.

### CODE REVIEW

**Comment by Yarovoy** [comment]
Hi, Ivan!

Do your know the best way to see what jsmpp sends to server? Is there any debug mode for that? Sorry for the question not related to this topic. :)

**Comment by pruh** [comment]
Hi Yuriy,

I think you should use some network protocol analyzer. For example, take a look at [WireShark](http://www.wireshark.org/)

**Comment by Yarovoy** [comment]
Thanks! That is exactly I want.

**Comment by uudashr** [comment]
Nice... merged

**Pull request merged**
